export const TREEVIEW = [
  {
    key: 'group0',
    type: 'group',
    expanded: true,
    children: [
      {
        key: 'group',
        type: 'group',
        data: {
          attributeType: null,
          lookupCode: null,
          operator: null,
          districtiveString: '',
          isValid: false,
          relation: '&&',
          mathOperation: null,
        },
        parent: null,
        children: [
          {
            key: 'attribute4',
            type: 'attribute',
            data: {
              attributeType: null,
              lookupCode: null,
              operator: null,
              districtiveString: '',
              isValid: false,
              relation: '&&',
              mathOperation: null,
            },
            parent: null,
            checked: true,
          },
          {
            key: 'attribute5',
            type: 'attribute',
            data: {
              attributeType: null,
              lookupCode: null,
              operator: null,
              districtiveString: '',
              isValid: false,
              relation: '&&',
              mathOperation: null,
            },
            checked: true,
            parent: null,
          },
        ],
      },
      {
        key: 'group1',
        type: 'group',
        expanded: true,
        children: [
          {
            key: 'attribute2',
            type: 'attribute',
            data: {
              attributeType: null,
              lookupCode: null,
              operator: null,
              districtiveString: '',
              isValid: false,
              relation: '&&',
              mathOperation: null,
            },
            parent: null,
            checked: true,
          },
          {
            key: 'attribute3',
            type: 'attribute',
            data: {
              attributeType: null,
              lookupCode: null,
              operator: null,
              districtiveString: '',
              isValid: false,
              relation: '&&',
              mathOperation: null,
            },
            parent: null,
            checked: true,
          },
          {
            key: 'group2',
            type: 'group',
            expanded: true,
            children: [
              {
                key: 'attribute4',
                type: 'attribute',
                data: {
                  attributeType: null,
                  lookupCode: null,
                  operator: null,
                  districtiveString: '',
                  isValid: false,
                  relation: '&&',
                  mathOperation: null,
                },
                parent: null,
                checked: true,
              },
              {
                key: 'attribute5',
                type: 'attribute',
                data: {
                  attributeType: null,
                  lookupCode: null,
                  operator: null,
                  districtiveString: '',
                  isValid: false,
                  relation: '&&',
                  mathOperation: null,
                },
                checked: true,
                parent: null,
              },
            ],
            parent: null,
          },
        ],
        parent: null,
      },
      {
        key: 'group3',
        type: 'group',
        expanded: true,
        children: [
          {
            key: 'attribute6',
            type: 'attribute',
            data: {
              attributeType: null,
              lookupCode: null,
              operator: null,
              districtiveString: '',
              isValid: false,
              relation: '&&',
              mathOperation: null,
            },
            parent: null,
            checked: true,
          },

          {
            key: 'group',
            type: 'group',
            data: {
              attributeType: null,
              lookupCode: null,
              operator: null,
              districtiveString: '',
              isValid: false,
              relation: '&&',
              mathOperation: null,
            },
            children: [
              {
                key: 'attribute4',
                type: 'attribute',
                data: {
                  attributeType: null,
                  lookupCode: null,
                  operator: null,
                  districtiveString: '',
                  isValid: false,
                  relation: '&&',
                  mathOperation: null,
                },
                parent: null,
                checked: true,
              },
              {
                key: 'attribute5',
                type: 'attribute',
                data: {
                  attributeType: null,
                  lookupCode: null,
                  operator: null,
                  districtiveString: '',
                  isValid: false,
                  relation: '&&',
                  mathOperation: null,
                },
                checked: true,
                parent: null,
              },
            ],
            checked: true,
            parent: null,
          },
        ],
        parent: null,
      },
      {
        key: 'group3',
        type: 'group',
        expanded: true,
        children: [
          {
            key: 'attribute6',
            type: 'attribute',
            data: {
              attributeType: null,
              lookupCode: null,
              operator: null,
              districtiveString: '',
              isValid: false,
              relation: '&&',
              mathOperation: null,
            },
            parent: null,
            checked: true,
          },
          {
            key: 'attribute7',
            type: 'attribute',
            data: {
              attributeType: null,
              lookupCode: null,
              operator: null,
              districtiveString: '',
              isValid: false,
              relation: '&&',
              mathOperation: null,
            },
            checked: true,
            parent: null,
          },
          {
            key: 'group',
            type: 'group',
            data: {
              attributeType: null,
              lookupCode: null,
              operator: null,
              districtiveString: '',
              isValid: false,
              relation: '&&',
              mathOperation: null,
            },
            checked: true,
            parent: null,
            children: [
              {
                key: 'attribute4',
                type: 'attribute',
                data: {
                  attributeType: null,
                  lookupCode: null,
                  operator: null,
                  districtiveString: '',
                  isValid: false,
                  relation: '&&',
                  mathOperation: null,
                },
                parent: null,
                checked: true,
              },
              {
                key: 'attribute5',
                type: 'attribute',
                data: {
                  attributeType: null,
                  lookupCode: null,
                  operator: null,
                  districtiveString: '',
                  isValid: false,
                  relation: '&&',
                  mathOperation: null,
                },
                checked: true,
                parent: null,
              },
            ],
          },
        ],
        parent: null,
      },
    ],
  },
];
